apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: zero-one-run-
  namespace: tekton-builds
spec:
  serviceAccountName: default
  pipelineRef:
    name: zero-one
  workspaces:
  - name: pipeline-ws
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Mi
        accessModes:
          - ReadWriteOnce
